import Head from 'next/head'
import { Header } from 'components/Header'
import Image from 'next/image'
import { readFile, stat } from 'fs/promises'

export default function Comic ({ img, alt, title, width, height }) {
  return (
    <div>
      <Head>
        <title>xkcd - Comics details</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Header />
      <main>
        <section className='max-w-lg m-auto'>
          <h1 className='font-bold'>{title}</h1>
          <Image
            width={width}
            height={height}
            layout='intrinsic'
            objectFit='contain'
            src={img}
            alt={alt}
          />
          <p>{alt}</p>
        </section>
      </main>
    </div>
  )
}

export async function getStaticPaths () {
  return {
    paths: [{ params: { id: '2500' } }],
    fallback: true
  }
}

export async function getStaticProps ({ params }) {
  const { id } = params

  console.log(id)

  const content = await readFile(`./comics/${id}.json`, 'utf8')
  const comic = JSON.parse(content)

  const idNumber = +id
  const prevId = idNumber - 1
  const nextId = idNumber + 1

  const results = await Promise.allSettled([
    stat(`./comics/${prevId}.json`),
    stat(`./comics/${nextId}.json`)
  ])

  return {
    props: {
      ...comic
    } // will be passed to the page component as props
  }
}
