import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { Header } from '../components/Header'
import { readdir, readFile } from 'fs/promises'

export default function Home ({ latesComics }) {
  // console.log({ latesComics })
  return (
    <>
      <Head>
        <title>xkcd - Comics developers</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Header />
      <main>
        <h2 className='text-xl font-semibold text-center mb-10'>Comics</h2>
        <section className='columns-1 sm:columns-2 md:columns-3 gap-2 max-w-md m-auto'>
          {latesComics.map(comic => (
            <Link href={`/comic/${comic.id}`} key={comic.id}>
              <a className='mb-4 pb-4'>
                <h3 className='font-semibold text-sm text-center pb-2'>
                  {comic.title}
                </h3>

                <Image
                  width={comic.width}
                  height={comic.height}
                  layout='intrinsic'
                  objectFit='contain'
                  src={comic.img}
                  alt={comic.alt}
                />
              </a>
            </Link>
          ))}
        </section>
      </main>
    </>
  )
}

export async function getStaticProps (context) {
  const files = await readdir('./comics')
  const latestComicsFiles = files.slice(-10, files.length)

  const promisesReadFiles = latestComicsFiles.map(async file => {
    const content = await readFile(`./comics/${file}`, 'utf8')
    return JSON.parse(content)
  })
  const latesComics = await Promise.all(promisesReadFiles)

  return {
    props: {
      latesComics: latesComics
    } // will be passed to the page component as props
  }
}
